### ISSUE TITLE
pylibsrcml fails to load on Windows

### ISSUE THREAD

**Issue by Joshua2000B** [srcML/pylibsrcml#3]
Importing pylibsrcml fails on Windows machines in the cytpes library - investigate fixes

**Comment by TTangNingzhi** [comment]
I also come across the same error: Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python310\lib\site-packages\pylibsrcml\srcml.py", line 14, in <module>
    import pylibsrcml.srcml_archive
  File "C:\Python310\lib\site-packages\pylibsrcml\srcml_archive.py", line 12, in <module>
    from pylibsrcml.globals import libsrcml
  File "C:\Python310\lib\site-packages\pylibsrcml\globals.py", line 46, in <module>
    libsrcml = cdll.LoadLibrary(LIBSRCML_PATH)
  File "C:\Python310\lib\ctypes\__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python310\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 87] Parameter Error.

**Comment by mjdecker** [comment]
It looks like Python can't find libsrcml.  

Can you let us know what version of Windows you have, how you installed srcML, and where you have installed it to?

**Comment by oSumAtrIX** [comment]
Issue still occurs. Runnig Windows 11, Python 3.10.1 from Microsoft Store.

**Comment by Joshua2000B** [comment]
This has been fixed in the rework branch. The reworked pylibsrcml will be released alongside the next version of srcML and libsrcml, which is slated to happen soon.

**Comment by Joshua2000B** [comment]
pylibsrcml will now search multiple locations for libsrcml. Libsrcml must be installed through a standard installer or built and installed from source.
